/*
 * File: app/store/ContactStore.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ContactTest.store.ContactStore', {
    extend: 'Ext.data.Store',

    requires: [
        'ContactTest.model.ContactModel',
        'Ext.data.proxy.Rest',
        'Ext.data.reader.Json',
        'Ext.data.writer.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoDestroy: false,
            storeId: 'ContactStore',
            autoSync: true,
            model: 'ContactTest.model.ContactModel',
            proxy: {
                type: 'rest',
                url: 'http://contacty.dev/contact/',
                useDefaultXhrHeader: false,
                format: 'json',
                reader: {
                    type: 'json',
                    keepRawData: true,
                    rootProperty: 'data'
                },
                writer: {
                    type: 'json',
                    writeAllFields: true,
                    writeRecordId: false,
                    encode: true,
                    rootProperty: 'data'
                }
            }
        }, cfg)]);
    }
});