/*
 * File: app/view/ContactGridPanel.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ContactTest.view.ContactGridPanel', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.contactgridpanel',

    requires: [
        'ContactTest.view.ContactGridPanelViewModel',
        'Ext.view.Table',
        'Ext.grid.column.Column',
        'Ext.form.field.Text',
        'Ext.grid.plugin.RowEditing',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'contactgridpanel'
    },
    reference: 'ContactsGridPanel',
    dock: 'top',
    height: 700,
    itemId: 'mygridpanel',
    width: '100%',
    title: 'Contacts',
    autoLoad: true,
    store: 'ContactStore',
    defaultListenerScope: true,

    viewConfig: {
        liquidLayout: true,
        modelValidation: false,
        loadingText: 'Loading Contacts...'
    },
    columns: [
        {
            xtype: 'gridcolumn',
            dataIndex: 'id',
            text: 'ID',
            editor: {
                xtype: 'textfield',
                readOnly: true,
                editable: false
            }
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'name',
            text: 'Name',
            editor: {
                xtype: 'textfield',
                allowBlank: false
            }
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'identification',
            text: 'Identification',
            editor: {
                xtype: 'textfield'
            }
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'email',
            text: 'Email',
            editor: {
                xtype: 'textfield'
            }
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'phonePrimary',
            text: 'Phone Primary',
            editor: {
                xtype: 'textfield'
            }
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'phoneSecondary',
            text: 'Phone Secondary',
            editor: {
                xtype: 'textfield'
            }
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'fax',
            text: 'Fax',
            editor: {
                xtype: 'textfield'
            }
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'mobile',
            text: 'Mobile',
            editor: {
                xtype: 'textfield'
            }
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'observations',
            text: 'Observations',
            editor: {
                xtype: 'textfield'
            }
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'address',
            text: 'Address',
            editor: {
                xtype: 'textfield'
            }
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'type',
            text: 'Type',
            editor: {
                xtype: 'textfield'
            }
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'seller',
            text: 'Seller',
            editor: {
                xtype: 'textfield'
            }
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'term',
            text: 'Term',
            editor: {
                xtype: 'textfield'
            }
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'priceList',
            text: 'Price List',
            editor: {
                xtype: 'textfield'
            }
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'internalContacts',
            text: 'Internal Contacts',
            editor: {
                xtype: 'textfield'
            }
        }
    ],
    plugins: [
        {
            ptype: 'rowediting',
            clicksToEdit: 1,
            autoUpdate: true,
            listeners: {
                edit: 'onRowEditingEdit',
                canceledit: 'onRowEditingCanceledit'
            }
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'button',
                    text: 'Add Contact'
                },
                {
                    xtype: 'button',
                    text: 'Delete Selected Contact'
                }
            ]
        }
    ],

    onRowEditingEdit: function(editor, context, eOpts) {

    },

    onRowEditingCanceledit: function(editor, context, eOpts) {

    }

});